name: Robot Framework API Tests

# Trigger on push and pull requests to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-jsonlibrary

      # Step 4: Run Robot Framework tests
      - name: Run Robot Framework API Tests
        run: |
          robot --outputdir reports tests/

      # Step 5: Upload test results
      - name: Upload Robot Framework results
        uses: actions/upload-artifact@v3
        with:
          name: robot-results
          path: reports/
